facecollector/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('faces/', views.faces_index, name='index'),
  # path('camera_feed', views.camera_feed, name='camera_feed')    
  path('faces/<int:face_id>/', views.faces_detail, name="detail"),
  path('faces/create/', views.FaceCreate.as_view(), name='faces_create'),
  # pk is what the django views is expecting as a param if we need one, which is short for primary key
  # aka the face_id
  path('faces/<int:face_id>/add_picture', views.add_picture, name='add_picture'),
  path('faces/<int:pk>/update/', views.FaceUpdate.as_view(), name='faces_update'),
  path('faces/<int:pk>/delete/', views.FaceDelete.as_view(), name='faces_delete'),
  path('faces/<int:face_id>/assoc_tag/<int:tag_id>/', views.assoc_tag, name='assoc_tag'),
  path('tags/', views.TagList.as_view(), name='tags_index'),
  path('tags/<int:pk>/', views.TagDetail.as_view(), name='tags_detail'),
  path('tags/create/', views.TagCreate.as_view(), name='tags_create'),
  path('tags/<int:pk>/update/', views.TagUpdate.as_view(), name='tags_update'),
  path('tags/<int:pk>/delete/', views.TagDelete.as_view(), name='tags_delete'),
  path('faces/<int:face_id>/upload_image', views.upload_picture, name='upload_picture'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tags_detail', kwargs={'pk': self.id})

GENDER = (
  ('F', 'Female'),
  ('M', 'Male'),
  ('N', 'Non-Binary'),
  ('R', 'Rather Not Say')
)

class Face(models.Model):
  name = models.CharField(max_length=100)
  age = models.IntegerField()
  golden_ratio = models.CharField(max_length=100)
  date = models.DateTimeField(auto_now_add=True)
  gender = models.CharField(
    max_length = 1,
    choices = GENDER,
    default = GENDER[2][0]
  )
  tags = models.ManyToManyField(Tag)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
      return reverse("detail", kwargs={"face_id": self.pk})
  
class Picture(models.Model):
  date = models.DateField(auto_now_add=True)
  url = models.URLField(max_length=200)
  face = models.ForeignKey(Face, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.id} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django import forms
from .models import Face, Picture, Tag

class FaceForm(forms.ModelForm):
  class Meta:
    model = Face
    fields = ('name', 'age', 'golden_ratio', 'gender')

    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'}),
      'age': forms.TextInput(attrs={'class': 'form-control'}),
      'golden_ratio': forms.TextInput(attrs={'class': 'form-control'}),
      'gender': forms.Select(attrs={'class': 'form-control'})
    }

class PictureForm(forms.ModelForm):
  class Meta:
    model = Picture
    fields = ('url',)

    widgets = {
      'url': forms.URLInput(attrs={'class': 'form-control'})
    }

class TagForm(forms.ModelForm):
  class Meta:
    model = Tag
    fields = ('name',)

    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'})
    }

main_app/views.py
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Face, Tag
from .forms import FaceForm, PictureForm, TagForm
import base64
import json
import time
# from django.views.decorators import gzip
import cv2
# import threading


# Create your views here.

# @gzip.gzip_page
def home(request):
    return render(request, 'index.html')

def about(request):
  return render(request, 'about.html')

def faces_index(request):
  faces = Face.objects.all()
  return render(request, 'faces/index.html', { 'faces': faces })

def faces_detail(request, face_id):
  face = Face.objects.get(id=face_id)
  picture_form = PictureForm()
  tags_face_doesnt_have = Tag.objects.exclude(id__in = face.tags.all().values_list('id'))

  return render(request, 'faces/detail.html', { 'face': face, 'picture_form': picture_form, 'tags': tags_face_doesnt_have })

def add_picture(request, face_id):
  form = PictureForm(request.POST)
  if form.is_valid():
    new_picture = form.save(commit=False)
    new_picture.face_id = face_id
    new_picture.save()
  return redirect('detail', face_id=face_id)


def upload_picture(request, face_id):
  current_time = time.time()
  file_name = str(face_id) + '-' + str(current_time).replace('.','-')
  full_file_path = f'main_app/static/images/{file_name}.jpeg'
  form = json.loads(request.body)
  print(form['image'],'<-image')
  header, encoded = form['image'].split(",", 1)
  with open(full_file_path, "wb") as fh:
    # fh.write(form)
    fh.write(base64.b64decode(encoded))
  # print(form)
  # if form.is_valid():
  #   new_picture = form.save(commit=False)
  #   new_picture.face_id = face_id
  #   new_picture.save()
  return redirect('detail', face_id=face_id)

def assoc_tag(request, face_id, tag_id):
  Face.objects.get(id=face_id).tags.add(tag_id)
  return redirect('detail', face_id=face_id)

class FaceCreate(CreateView):
    model = Face
    form_class = FaceForm
    # fields = '__all__' 

class FaceUpdate(UpdateView):
    model = Face
    form_class = FaceForm
    # fields = ['age', 'hotness'] 

class FaceDelete(DeleteView):
    model = Face 
    success_url = '/faces/'

class TagList(ListView):
    model = Tag

class TagDetail(DetailView):
    model = Tag

class TagCreate(CreateView):
    model = Tag
    form_class = TagForm

class TagUpdate(UpdateView):
    model = Tag
    form_class = TagForm

class TagDelete(DeleteView):
    model = Tag
    success_url = '/tags/'












# def camera_feed(request):
#   return StreamingHttpResponse(gen(VideoCamera()), content_type="multipart/x-mixed-replace; boundary=frame")

# class VideoCamera(object):
#     def __init__(self):
#         self.video = cv2.VideoCapture(0)
#         (self.grabbed, self.frame) = self.video.read()
#         threading.Thread(target=self.update, args=()).start()

#     def __del__(self):
#         self.video.release()

#     def get_frame(self):
#         image = self.frame
#         _, jpeg = cv2.imencode('.jpg', image)
#         return jpeg.tobytes()

#     def update(self):
#         while True:
#             (self.grabbed, self.frame) = self.video.read()

# def gen(camera):
#     while True:
#         frame = camera.get_frame()
#         yield (b'--frame\r\n'
#               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center mt-4">About Face Collector</h1>
{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
      defer
    ></script>
    <title>Face Collector</title>
  </head>
  <body class="bg-secondary">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">FC</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/faces">View all Faces</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'faces_create' %}">Add a Face</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tags_create' %}">Add a Tag</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tags_index' %}"
                >View all Tags</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main class="container">
      {% block content %} {% endblock %}
      <footer class="py-3 my-4 text-white">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item">
            <a href="/" class="nav-link px-2 text-reset">Home</a>
          </li>
          <li class="nav-item">
            <a href="/about" class="nav-link px-2 text-reset">About</a>
          </li>
          <li class="nav-item">
            <a href="/faces" class="nav-link px-2 text-reset">Faces</a>
          </li>
        </ul>
        <p class="text-center text-reset">© 2022 J<sup>2</sup>M</p>
      </footer>
    </main>
  </body>
</html>

main_app/templates/faces/detail.html
{% extends 'base.html' %} {% block content %}

<div class="row mt-5">
  <div class="col-6">
    <h2>{{ face.name }}'s Details</h2>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ face.name }}</h5>
        <p>Age: {{ face.age }}</p>
        <p>Golden Ratio: {{ face.golden_ratio }}</p>
        <p>Date: {{ face.date }}</p>
        <p>Gender: {{ face.get_gender_display }}</p>
      </div>

      <div class="card-body">
        <a class="btn btn-primary" href="{% url 'faces_update' face.id %}"
          >Edit</a
        >
        <a class="btn btn-danger" href="{% url 'faces_delete' face.id %}"
          >Delete</a
        >
      </div>
    </div>
  </div>
  <div class="col-6">
    <h2>Add a Picture for {{face.name}}</h2>
    <div class="card">
      <div class="card-body">
        <button id="start-camera">Start Camera</button>
        <video id="video" width="320" height="240" autoplay></video>
        <button id="click-photo">Click Photo</button>
        <canvas id="canvas" width="320" height="240"></canvas>
        {% csrf_token %} {% comment %}
        <form action="{% url 'add_picture' face.id %}" method="POST">
          {% csrf_token %} {{picture_form.as_p}}
          <input type="submit" class="btn btn-primary" value="Add Picture" />
        </form>
        {% endcomment %}
      </div>
    </div>
  </div>
</div>

<div class="row mt-3">
  <h2>Pictures</h2>
  {% for picture in face.picture_set.all %}
  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <img width="100%" src="{{ picture.url }}" />
        <p class="text-center">{{picture.date}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="row mt-3">
  <div class="col-6">
    <h3>{{face.name}}'s Tags</h3>
    <ul class="list-group">
      {% if face.tags.count %} {% for tag in face.tags.all %}
      <li class="list-group-item">{{tag.name}}</li>
      {% endfor %}
    </ul>
    {% else %}
    <h5>No Tags :(</h5>
    {% endif %}
  </div>
  <!-- Available tags will come after this line -->
  <div class="col-6">
    <h3>Available Tags</h3>
    <ul class="list-group">
      {% if tags.count %} {% for tag in tags.all %}
      <li class="list-group-item">
        {{tag.name}} -
        <form
          id="tag-form"
          action="{% url 'assoc_tag' face.id tag.id %}"
          method="post"
          class="d-inline"
        >
          {% csrf_token %}
          <a href="#" onclick="submitForm()">Add</a>
        </form>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <h5>{{face.name}} Already Has All Tags Available</h5>
    {% endif %}
  </div>
  <script>
    function submitForm() {
      let form = document.getElementById('tag-form');
      form.submit();
    }

    let buttonElem = document.getElementById('take-picture');
    let camera_button = document.querySelector('#start-camera');
    let video = document.querySelector('#video');
    let click_button = document.querySelector('#click-photo');
    let canvas = document.querySelector('#canvas');

    camera_button.addEventListener('click', async function () {
      let stream = await navigator.mediaDevices.getUserMedia({
        video: true,
        audio: false,
      });
      video.srcObject = stream;
    });

    click_button.addEventListener('click', function () {
      canvas
        .getContext('2d')
        .drawImage(video, 0, 0, canvas.width, canvas.height);
      let image_data_url = canvas.toDataURL('image/jpeg');
      let name = getCurrentTimestamp();
      console.log(name, '<-name');
      console.log(image_data_url, '<-image_data_url');

      sendBase64ToServer(name, image_data_url);
      // data url of the image
    });

    var sendBase64ToServer = function (name, base64) {
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      console.log(csrftoken, '<-csrftoken')
      const httpPost = new XMLHttpRequest(),
        path = 'upload_image',
        data = JSON.stringify({ image: base64 });
      console.log(data, '<-data');
      {% comment %} httpPost.onreadystatechange = function (err) {
        if (httpPost.readyState == 4 && httpPost.status == 200) {
          console.log(httpPost.responseText);
        } else {
          console.log(err);
        }
      }; {% endcomment %}
      // Set the content type of the request to json since that's what's being sent

      httpPost.open('POST', path, true);
      httpPost.setRequestHeader('Content-Type', 'application/json');
      httpPost.setRequestHeader('X-CSRFToken', csrftoken);
      httpPost.send(data);
    };

    function getCurrentTimestamp() {
      return Date.now();
    }
  </script>
  {% endblock %}
</div>

main_app/templates/faces/index.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center pb-3 my-4 text-white border-bottom">Faces</h1>

<div class="row">
  {% for face in faces %}
  <div class="col-lg-3">
    <div class="card mb-3">
      <a
        href="{% url 'detail' face.id %}"
        class="text-decoration-none text-reset"
      >
        <div class="card-body text-black">
          <h5 class="card-title">{{ face.name }}</h5>
          <p>Age: {{ face.age }}</p>
          <p>Golden Ratio: {{ face.golden_ratio }}</p>
          <p>Date: {{ face.date }}</p>
        </div>
      </a>
    </div>
  </div>
  {% if forloop.counter0|divisibleby:4 and forloop.counter0 > 3 %}
</div>
<div class="row">{% endif %} {% endfor %}</div>
{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center mt-4">Home Page</h1>
<div class="row">
  <div class="col-4 offset-4">
    {% comment %}
    <img width="100%" src="{% url 'camera_feed' %}" />
    {% endcomment %}
  </div>
</div>

{% endblock %}

main_app/templates/main_app/face_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Cat</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn btn-danger" />
  <a href="{% url 'detail' face.id %}" class="btn btn-success">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/face_form.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<div class="row">
  <div class="col-6">
    {% if object %}

    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add a Face</h1>
    {% endif %}

    <form action="" method="post">
      <!-- Django requires the following for security purposes -->
      {% csrf_token %}
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form }}
      <input type="submit" value="Submit!" class="btn btn-primary mt-3" />
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/tag_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Tag</h1>

<h4>Are you sure you want to delete the tag "{{ object.name }}"?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn btn-danger" />
  <a class="btn btn-primary" href="{% url 'tags_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/tag_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Tag Details</h1>

<div class="row">
  <div class="col-6 offset-3">
    <div class="card">
      <div class="card-body text-center">
        <h3 class="card-title">{{ tag.name }}</h3>
      </div>
      <div class="card-action text-center mb-3">
        <a class="btn btn-primary" href="{% url 'tags_update' tag.id %}"
          >Edit</a
        >
        <a class="btn btn-danger" href="{% url 'tags_delete' tag.id %}"
          >Delete</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/tag_form.html
{% extends 'base.html' %} {% block content %}
<div class="row">
  <div class="col-6">
    {% if object %}
    <h1>Edit {{object.name}}</h1>
    {% else %}
    <h1>Add Tag</h1>
    {% endif %}
    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="post">
      <!-- Django requires the following for security purposes -->
      {% csrf_token %}
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
      <input type="submit" value="Submit!" class="btn btn-primary mt-3" />
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/tag_list.html
{% extends 'base.html' %} {% block content %}

<h1>Tag List</h1>
<div class="row">
  <div class="col-4 offset-4">
    {% for tag in tag_list %}
    <a href="{% url 'tags_detail' tag.id %}">
      <div class="card">
        <div class="card-body">
          <span class="card-title">{{ tag.name }}</span>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}